### ISSUE TITLE
Adding Bandage to visual genome assembly

### ISSUE THREAD

**Issue by danejo3** [bioforensics/yeat#24]
Bandage (`Bioinformatics Application for Navigating De novo Assembly Graphs Easily`) is a GUI for visualizing the quality of various assemblers when recreating the genome. It was created by Ryan Wick, who also created `Unicycler`, and is one of the go-to tools for many in the community.

![](https://rrwick.github.io/Bandage/images/wiki/bandage_gui.png)

In order to use Bandage, users will need to provide `assembly graph` files. These files are used to represent the final assembly of a genome. Typically, popular assemblers like SPAdes will auto-generate them alongside the final contigs. For example, users will find an `assembly_graph.fastg` file in their output directory.

The following assembly graph files are supported by Bandage:
- LastGraph (Velvet)
- FASTG (SPAdes)
- Trinity.fasta
- ASQG
- GFA

**BASIC USAGE:** 

To use the see assembly result, for iOS, users will click: 
> File -> Load graph -> {Locate the assembly graph file}
> After loading the graph, on the left hand side, click on the `Draw graph`--underneath the `Draw Graph` section.

![image](https://user-images.githubusercontent.com/33472323/197854445-95bac5d3-bbc7-459d-9783-ebe74ed9a483.png)

(If you would like to learn more about what Bandage can do, look [here](https://rrwick.github.io/Bandage/), underneath the `Features` section.)

**Comment by danejo3** [comment]
How to download or install `Bandage`.

The quickest and easiest way to install Bandage is by going onto their main page and select the appropriate OS system you are using on https://rrwick.github.io/Bandage/.

If choosing this route, users will download a compressed file with the Bandage GUI and a test assembly graph file. 

Bang! It's ready to use!

However, if the user would rather install the software from the source, users will need to follow these steps on
https://github.com/rrwick/Bandage#building-from-source.

If done this way, users will **need** to install [Qt SDK](https://www.qt.io/download-open-source) and **must** get a version 5.15 or later. Furthermore, in order to use Qt, you **must** create an account!

**Comment by danejo3** [comment]
Help! I'm running into this popup when I try to run Bandage on iOS!

![image](https://user-images.githubusercontent.com/33472323/197857155-48ff336b-b50b-489d-af85-df1bfebcf877.png)

If you get this, the correct way to bypass this is by:
> Click on the `Apple` -> System Peferences -> Security & Privacy
> About middle'ish of the window, you'll see `Open Anyway` next to "Bandage.app" was blocked from use because it is not from an identified developer.
> Click `Open Anyway` and modify your system settings accordingly.

If your iOS device still fails to update the system settings for the application, a solution that I found was to install the application onto another device and transfer the app to the desired system.

For example, installed the iOS version on windows machine, used USB to transfer the downloaded file from windows onto iOS.

**Comment by danejo3** [comment]
**I did what you said but it still blocks me!**

If your iOS device still fails to update the system settings for the application, a solution that I found was to install the application onto another device and transfer the app to the desired system.

For example, installed the iOS version on windows machine, used USB to transfer the downloaded file from windows onto iOS.

**Comment by danejo3** [comment]
Currently YEAT has three available assemblers: SPAdes, MEGAHIT, and Unicycler. All assemblers produce assembly graph(s) but MEGAHIT.

The following files from these assemblers can be loaded into Bandage.

SPAdes (4):
- assembly_graph_after_simplification.gfa
- assembly_graph_with_scaffolds.gfa
- assembly_graph.fastg
- strain_graph.gfa

Unicycler (6):
- 001_best_spades_graph.gfa
- 002_overlaps_removed.gfa
- 003_bridges_applied.gfa
- 004_final_clean.gfa
- 005_polished.gfa
- assembly.gfa

**Comment by danejo3** [comment]
In order to see the visual results from MEGAHIT to Bandage, users will need to use `megahit_toolkit` provided by MEGAHIT. This tool is only available in **version 0.3.0+**.

https://github.com/voutcn/megahit/wiki/Visualizing-MEGAHIT's-contig-graph

![image](https://user-images.githubusercontent.com/33472323/197860439-c36dd81e-8676-4fd1-8438-69014cb263ff.png)

Note: the red box. 

Because of this tool, the number of files that can be loaded into Bandage from MEGAHIT can only be up to number of K-mers used in the assembly.

For example:

Megahit (8):
- k21 -> k21.fastg
- k29 -> k29.fastg
- k39 -> k39.fastg
- k59 -> k59.fastg
- k79 -> k79.fastg
- k99 -> k99.fastg
- k119 -> k119.fastg
- k141 -> k141.fastg

**Comment by danejo3** [comment]
With all this information collected and compiled in this issue thread, here are my thoughts on how we can include "support" for bandage in YEAT.

Because Bandage is its' own software, I think we'll need to add in the documentation notifying users that they will need to either download the Bandage GUI or create the Bandage from the source code.

For us to "support" Bandage, I was thinking of creating a directory in `analysis/bandage` and creating separate directories within that directory for each assembly algorithm used. For example, `analysis/bandage/spades`.

The question that comes to my mind is, in the following posts above, should I symlink or copy all of the assembly graph files into these files? What assembly graph files are useful and which are not?

Finally and ultimately, is adding this `analysis/bandage` "support" necessary if users can go directly into the `analysis/{assembler}` themselves if Bandage is not included in YEAT?

**Comment by danejo3** [comment]
In additional to the post above, if we do go about creating a `analysis/bandage` directory. Depending on how we go about how many assembly graph files we want to add to them, we will need to change the current `Snakemake` file.

**Comment by danejo3** [comment]
Another question: MEAGHIT has a number of k-mers that it uses. If we were to select one specific k-mer, how would we know which one is the best? By default, and from examples that I'm seeing from other people, k-99 is what people are going for? Any reasons why this is the case?

**Comment by standage** [comment]
There's a lot here, and I won't be able to respond to it all immediately. Briefly, I envisioned Bandage "support" to involve generating some kind of default plot as part of the core workflow, or at least aggregating Bandage-compatible input files for all assemblers to the extent possible with reasonable effort.

A quick Google search led me to [this thread](https://github.com/rrwick/Bandage/issues/14) and [this page on the Bandage wiki](https://github.com/rrwick/Bandage/wiki/Command-line), confirming that Bandage can indeed be scripted on the command line. That's very relevant to the discussion here.

But many of your other points are relevant and deserve discussion. I'll return to this thread as soon as I can.

**Comment by danejo3** [comment]
I found a package that converts `fasta` files into `gfa` and vice-versa.

This will allow us to visualize the final config file created by `MEGAHIT` since its internal tool can only convert intermediate k-mer config files. (See comment about `megahit_toolkit`.)

https://github.com/vgl-hub/gfastats#usage
